### ISSUE TITLE
Checklist for apps

### ISSUE THREAD

**Issue by SwikritiT** [SwikritiT/droneUpdater#1]
- [ ] activity @sushmita56 
- [ ]  admin_audit @SagarGi 
- [ ]  afterlogic @SagarGi 
- [ ]   announcementcenter @SagarGi 
- [ ]  bookmarks @SagarGi 
- [ ]  brute_force_protection @amrita-shrestha 
- [ ]  calendar @sushmita56 
- [ ]  contacts @sushmita56
- [ ]  customgroups @sushmita56
- [ ]  diagnostics @sushmita56
- [ ]  enterprise_key @sushmita56
- [ ]  files_antivirus @sushmita56
- [ ]  files_classifier @sushmita56
- [ ]  files_clipboard @sushmita56
- [ ]  files_external_dropbox @sushmita56
- [ ]  files_external_ftp @sushmita56
- [ ] files_external_s3 @amrita-shrestha 
- [ ] files_ldap_home @amrita-shrestha
- [ ] files_lifecycle @amrita-shrestha
- [ ] files_mediaviewer @amrita-shrestha
- [ ] files_pdfviewer @amrita-shrestha
- [ ] files_primary_s3 @amrita-shrestha
- [ ] files_texteditor @amrita-shrestha
- [ ] files_textviewer @amrita-shrestha
- [ ] firewall @amrita-shrestha
- [ ] gallery @amrita-shrestha
- [ ] graphapi @grgprarup 
 - [ ] guests @grgprarup 
 - [ ]  impersonate @grgprarup
 - [ ]  market @grgprarup
 - [ ] metrics @grgprarup
 - [ ] music @grgprarup
 - [ ] notes @grgprarup
 - [ ] objectstore @grgprarup
- [ ] openidconnect @grgprarup
 - [ ] password_policy @grgprarup
- [ ] ransomware_protection @SagarGi 
- [ ]  richdocuments @SagarGi
- [ ] search_elastic @SagarGi
- [ ] sharepoint @SagarGi
- [ ] systemtags_management @SagarGi
- [ ] tasks @SagarGi
- [ ] templateeditor @SagarGi
- [ ] theme-enterprise @sushmita56
- [ ] twofactor_backup_codes @sushmita56 
- [ ] twofactor_privacyidea @sushmita56 
- [ ] twofactor_totp @amrita-shrestha 
- [ ] user_ldap @amrita-shrestha 
- [ ] user_shibboleth @amrita-shrestha 
- [ ] windows_network_drive @grgprarup 
- [ ]  wopi @grgprarup 
- [ ] workflow @grgprarup 
- [ ] web @amrita-shrestha 
- [ ] ocis @grgprarup 
- [ ] core @grgprarup
